name = "ai-threads"
compatibility_date = "2024-09-16"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

# local では .dev.vers に入力
# [vars]
# OIDC_AUTH_SECRET = "${OIDC_AUTH_SECRET}"
# OIDC_ISSUER = "${OIDC_ISSUER}"
# OIDC_CLIENT_ID = "${OIDC_CLIENT_ID}"
# OIDC_CLIENT_SECRET = "${OIDC_CLIENT_SECRET}"
# OIDC_REDIRECT_URI = "${OIDC_REDIRECT_URI}"
# OIDC_SCOPES = "${OIDC_SCOPES}"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "ai-threads"
migrations_dir = "drizzle/migrations"
database_id = "${CLOUDFLARE_DATABASE_ID}"

# [ai]
# binding = "AI"
